export default {
    ts: "TypeScript",
    cpp: "C++",
    assembly: "Assembly",
    elf: "ELF",
    pe: "PE",
    ida: "IDA Pro",
    x64dbg: "x64dbg",
    httpDebugger: "HTTP Debugger Pro",
    procmon: "Process Monitor",
    burp: "Burp Suite Professional",
    js: "JavaScript",
    python: "Python",
    sqlite: "SQLite",
    mongo: "MongoDB",
    postgreSql: "PostgreSQL",
    html: "HTML",
    css: "CSS",
    sass: "SASS",
    scss: "SCSS",
    less: "Less",
    stylus: "Stylus",
    ejs: "EJS",
    jinja: "Jinja2",
    node: "Node.js",
    vscode: "VSCode",
    nvim: "NeoVim",
    figma: "Figma",
    git: "Git & GitHub",
    xfce: "XFCE",
    react: "React",
    discordJs: "Discord.js",
    flask: "Flask",
    quart: "Quart",
    express: "Express",
    rtk: "RTK",
    zod: "Zod",
    webpack: "WebPack",
    pug: "Pug",
    gulp: "Gulp",
    next: "Next",
    deno: "Deno",
    pixijs: "PixiJS",
    preact: "Preact",
    infosec: "Information Security",
    malware: "Malware Analysis",
    "reverse-engineering": "Reverse Engineering"
}